<template>
    <component :is="componentName" v-bind="props" v-on="listeners" :class="classNames" :style="style">{{componentName}}</component>
</template>


<script>
import adapter from './adapter'

export default {
    components: {
        Button: () => import('@/components/Basic/Button'),
        Figure: () => import('@/components/Basic/Figure'),
        Icon: () => import('@/components/Basic/Icon'),
        CustomText: () => import('@/components/Basic/Text'),
        Calendar: () => import('@/components/Date/Calendar'),
        Clock: () => import('@/components/Date/Clock'),
        Moment: () => import('@/components/Date/Moment'),
        Timer: () => import('@/components/Date/Timer'),
        Account: () => import('@/components/Form/Account'),
        Cart: () => import('@/components/Form/Cart'),
        Checklist: () => import('@/components/Form/Checklist'),
        Checks: () => import('@/components/Form/Checks'),
        Choice: () => import('@/components/Form/Choice'),
        Collection: () => import('@/components/Form/Collection'),
        Comments: () => import('@/components/Form/Comments'),
        Counter: () => import('@/components/Form/Counter'),
        Editable: () => import('@/components/Form/Editable'),
        Keypad: () => import('@/components/Form/Keypad'),
        Note: () => import('@/components/Form/Note'),
        Pickers: () => import('@/components/Form/Pickers'),
        Radios: () => import('@/components/Form/Radios'),
        Rate: () => import('@/components/Form/Rate'),
        Register: () => import('@/components/Form/Register'),
        Search: () => import('@/components/Form/Search'),
        CustomSelect: () => import('@/components/Form/Select'),
        Slider: () => import('@/components/Form/Slider'),
        CustomSwitch: () => import('@/components/Form/Switch'),
        Tag: () => import('@/components/Form/Tag'),
        Transfer: () => import('@/components/Form/Transfer'),
        Upload: () => import('@/components/Form/Upload'),
        Votes: () => import('@/components/Form/Votes'),
        Affix: () => import('@/components/Layout/Affix'),
        Grid: () => import('@/components/Layout/Grid'),
        Headline: () => import('@/components/Layout/Headline'),
        Parallel: () => import('@/components/Layout/Parallel'),
        Squares: () => import('@/components/Layout/Squares'),
        Bounce: () => import('@/components/Motion/Bounce'),
        Carousel: () => import('@/components/Motion/Carousel'),
        Flash: () => import('@/components/Motion/Flash'),
        LandInText: () => import('@/components/Motion/LandInText'),
        Lazy: () => import('@/components/Motion/Lazy'),
        Mawaru: () => import('@/components/Motion/Mawaru'),
        Multiple: () => import('@/components/Motion/Multiple'),
        Pulse: () => import('@/components/Motion/Pulse'),
        Reveal: () => import('@/components/Motion/Reveal'),
        Scroll: () => import('@/components/Motion/Scroll'),
        Shake: () => import('@/components/Motion/Shake'),
        Shine: () => import('@/components/Motion/Shine'),
        Slide: () => import('@/components/Motion/Slide'),
        Snow: () => import('@/components/Motion/Snow'),
        Spin: () => import('@/components/Motion/Spin'),
        Stagger: () => import('@/components/Motion/Stagger'),
        Stroke: () => import('@/components/Motion/Stroke'),
        Swing: () => import('@/components/Motion/Swing'),
        Turn: () => import('@/components/Motion/Turn'),
        Wander: () => import('@/components/Motion/Wander'),
        Wave: () => import('@/components/Motion/Wave'),
        Anchor: () => import('@/components/Navigation/Anchor'),
        Arrow: () => import('@/components/Navigation/Arrow'),
        Cascader: () => import('@/components/Navigation/Cascader'),
        Columns: () => import('@/components/Navigation/Columns'),
        Crumb: () => import('@/components/Navigation/Crumb'),
        Link: () => import('@/components/Navigation/Link'),
        Menu: () => import('@/components/Navigation/Menu'),
        Paginations: () => import('@/components/Navigation/Paginations'),
        Steps: () => import('@/components/Navigation/Steps'),
        Tabs: () => import('@/components/Navigation/Tabs'),
        Toolbar: () => import('@/components/Navigation/Toolbar'),
        Tree: () => import('@/components/Navigation/Tree'),
        Article: () => import('@/components/Presention/Article'),
        Avatar: () => import('@/components/Presention/Avatar'),
        Board: () => import('@/components/Presention/Board'),
        Box: () => import('@/components/Presention/Box'),
        Calculator: () => import('@/components/Presention/Calculator'),
        Card: () => import('@/components/Presention/Card'),
        Cover: () => import('@/components/Presention/Cover'),
        Curtain: () => import('@/components/Presention/Curtain'),
        Dashboard: () => import('@/components/Presention/Dashboard'),
        Divider: () => import('@/components/Presention/Divider'),
        Editor: () => import('@/components/Presention/Editor'),
        Exhibit: () => import('@/components/Presention/Exhibit'),
        Gallery: () => import('@/components/Presention/Gallery'),
        List: () => import('@/components/Presention/List'),
        Loading: () => import('@/components/Presention/Loading'),
        CustomMarker: () => import('@/components/Presention/Marker'),
        CustomMask: () => import('@/components/Presention/Mask'),
        Pack: () => import('@/components/Presention/Pack'),
        CustomPattern: () => import('@/components/Presention/Pattern'),
        Player: () => import('@/components/Presention/Player'),
        Pocket: () => import('@/components/Presention/Pocket'),
        Progress: () => import('@/components/Presention/Progress'),
        Reader: () => import('@/components/Presention/Reader'),
        Shelf: () => import('@/components/Presention/Shelf'),
        Skeleton: () => import('@/components/Presention/Skeleton'),
        Sticky: () => import('@/components/Presention/Sticky'),
        Ticket: () => import('@/components/Presention/Ticket'),
        Translator: () => import('@/components/Presention/Translator'),
        Alert: () => import('@/components/Reaction/Alert'),
        Collapse: () => import('@/components/Reaction/Collapse'),
        Confirm: () => import('@/components/Reaction/Confirm'),
        Dnd: () => import('@/components/Reaction/Dnd'),
        Drawer: () => import('@/components/Reaction/Drawer'),
        Dropdown: () => import('@/components/Reaction/Dropdown'),
        CustomFilter: () => import('@/components/Reaction/Filter'),
        Hover: () => import('@/components/Reaction/Hover'),
        Ink: () => import('@/components/Reaction/Ink'),
        Message: () => import('@/components/Reaction/Message'),
        Modal: () => import('@/components/Reaction/Modal'),
        Popover: () => import('@/components/Reaction/Popover'),
        Promp: () => import('@/components/Reaction/Promp'),
        Pull: () => import('@/components/Reaction/Pull'),
        Sketch: () => import('@/components/Reaction/Sketch'),
        Tip: () => import('@/components/Reaction/Tip'),
        Toggle: () => import('@/components/Reaction/Toggle'),
    },

    data() {
        const componentName = this.$route.params.page
        const { props, listeners, classNames, style } = adapter[componentName]
        return {
            componentName,
            props,
            listeners,
            classNames,
            style,
        }
    },
}
</script>